### ISSUE TITLE
:pray: Hi, please provide a package on sdkman :nerd_face: 

### ISSUE THREAD

**Issue by adriens** [maciejwalkowiak/just#1]
An always increasing number of people use [`SDKMAN!`](https://sdkman.io/) to install software.

I saw that you were using [JReleaser, and as it manages `sdkman`](https://jreleaser.org/guide/latest/configuration/packagers/sdkman.html) that would pretty cool :smile_cat:

**Comment by aalmiray** [comment]
One thing to be considered before is figuring out if Sdkman allows non Open Source tools to be distributed. JUST is not Open Source and as far as I can tell every SDK listed as https://sdkman.io/sdks is Open Source.

There's no mention of license restrictions at https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process

cc: @helpermethod

**Comment by helpermethod** [comment]
Hi @adriens, @aalmiray,

yes, we don't publish any commercial tools, as we've got burned by it in the past.

Furthermore, we require archives to be in a special, SDK-like format (i.e. at top-level directory with a `/bin` directory underneath), something like

```
mytool-1.0.0.jar
  /bin
    mytool
```

which is not the case with `just` (yet).

**Comment by aalmiray** [comment]
> yes, we don't publish any commercial tools, as we've got burned by it in the past.

May need to make this restriction explicit in the docs 😉

**Comment by maciejwalkowiak** [comment]
@adriens in such case I think the next step would be to add publishing to Snapcraft for Linux distors that use Snap. This would leave us with:

- Homebrew for MacOS
- Scoop for Windows
- Snap for Linux

I imagine SDKMan would be the most convenient but since it's not a possibility I think these 3 is a good enough solution

**Comment by adriens** [comment]
So I close the issue ?

**Comment by maciejwalkowiak** [comment]
Yes. Closing in favour of #4

**Comment by adriens** [comment]
:+1:
