### ISSUE TITLE
Quarkus support?

### ISSUE THREAD

**Issue by tigerinus** [maciejwalkowiak/just#34]
Great tool for Spring Boot developers.

Any thoughts on supporting Quarkus, and/or other frameworks?

**Comment by maciejwalkowiak** [comment]
I have it in mind but considering Quarkus has [Dev Mode](https://quarkus.io/guides/maven-tooling#dev-mode) and [Dev Services](https://quarkus.io/guides/dev-services) I am not sure what gap could Just fill. Do you have some ideas?
