### ISSUE TITLE
just build native-image from documentation does not exist on Mac

### ISSUE THREAD

**Issue by DennisBecker** [maciejwalkowiak/just#38]
The documentation shows that you have to use `` to build a docker image with a native executable. `just` shows an error and that you have to use `native_image`. So, which is the preferred target?

```
just build native-image

Invalid value for positional parameter at index 0 (<buildTarget>): there is no target native-image. Choose one of: [image, native, jar, native_image]
Usage: just build [--quick] [--skip-tests] [<buildTarget>]
builds application
      [<buildTarget>]   one of: jar, native, image, native-image
      --quick           runs fast build, skip tests, skips docs generation and
                          all possible checks
      --skip-tests      skips tests
```

I have installed just 0.12.0 with brew on a Macbook Pro M1.

**Comment by maciejwalkowiak** [comment]
This has been reported in #20 and will be fixed in the next release. Right now please use `just build native_image`.

**Comment by DennisBecker** [comment]
Sorry, seems I have not searched correctly
