### ISSUE TITLE
0.13.0 version licence expired

### ISSUE THREAD

**Issue by ArtyomGabeev** [maciejwalkowiak/just#53]
Hi,

License expired (valid until: 2023-04-30).

Any plans for 0.14.0? 

Thank you!

**Comment by ranma2913** [comment]
Help, Same issue. JUST is dead in the water right now because of the built in license expiry:

![image](https://github.com/maciejwalkowiak/just/assets/4295880/91934d0c-0b7c-4142-8091-304d9270a4f0)

**Comment by jerlysonsantos** [comment]
I've same issue

**Comment by LuisMCunha** [comment]
Is the project dead?

**Comment by maciejwalkowiak** [comment]
@LuisMCunha @jerlysonsantos @ranma2913 @ArtyomGabeev Apologies for a delay, I had some serious downtime. Just 0.14.0 released with no new changes other than license extended till the end of the year.
