### ISSUE TITLE
Not ruining in Linux 

### ISSUE THREAD

**Issue by poranchowdury** [maciejwalkowiak/just#6]
![image](https://user-images.githubusercontent.com/111353340/207798597-6e175134-c9b1-4b76-a8bc-155243aec9f9.png)

just: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by just)
just: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by just)

**Comment by maciejwalkowiak** [comment]
Which Linux version do you use? It works on Linux but requires GLIBC 2.34. It works on the Ubuntu 22.04 (LTS)

**Comment by poranchowdury** [comment]
Ubuntu 20.04.5 LTS

**Comment by maciejwalkowiak** [comment]
I'll see what I can do

**Comment by maciejwalkowiak** [comment]
Closed in favour of #10
