### ISSUE TITLE
A project not using Boot as direct dependency fails to start

### ISSUE THREAD

**Issue by odrotbohm** [maciejwalkowiak/just#7]
I have a project that has its Spring Boot parent defined in a parent itself. This causes `just run` to fail with

```
just   | Spring Boot not configured. `just run` supports (for now) only Spring Boot projects.
```

**Comment by maciejwalkowiak** [comment]
Thanks for reporting! To determine is it is a Spring Boot project it checks for the presence of `spring-boot-maven-plugin` (otherwise it won't be able to start `spring-boot:run` goal). I overlooked the possibility that the plugin is configured in parent pom or in a a profile. This will be improved in the next release.

**Comment by odrotbohm** [comment]
By the way: the problem also occurs for the plugin declared in a profile activated by default. I guess that's a tough one to tackle, but I sometimes use activated-by-default profiles to be able to group dependencies and plugins by "purpose". I am not certain how common that is, though.

**Comment by maciejwalkowiak** [comment]
I am thinking of following:

- when checking for the presence of `spring-boot-maven-plugin` take into account the active profiles (including ones set with `just.run.maven.profiles`
- determine if plugin is present by calling `mvn spring-boot:help` and analysing the response or just checking if there is any dependency to any `spring-boot` module. With the latter there will be some edge cases where it fails but likely less than 0.1% of projects

The workaround for the edge cases could be a configuration property that sets the framework and avoids check like `just.run.framework`
