### ISSUE TITLE
How to update when you install using homebrew

### ISSUE THREAD

**Issue by arunkpatra** [maciejwalkowiak/just#9]
@maciejwalkowiak maybe we could add a `How to Update` section in the README.

I am proposing `just update`. What say? Would be happy to take this up and submit a PR.

Also, would you please add `Question` label on this repo; because, this is technically not an Issue, but just a question. Maybe we can setup a Discord Server, or Gitter Chat, whatever you would think best.

**Comment by maciejwalkowiak** [comment]
Homebrew and Scoop have its own update mechanism. I am not sure how this self-update could be implemented considering it must support Windows/Linux/MacOS and find out if it has been installed manually or with a package manager?

**Comment by arunkpatra** [comment]
Yeah I see you point, especially given the various different ways to install it as you have pointed out. IMO, we could park it for now.

**Comment by maciejwalkowiak** [comment]
Yes, I think it is ok to rely on the update mechanisms of the package managers.
